import type { ScanReport } from "../types";

const STATUS_ICONS: Record<string, string> = {
	passed: "PASSED",
	warning: "WARNING",
	failed: "FAILED",
	blocked: "BLOCKED",
	error: "ERROR",
};

const SEVERITY_ICONS: Record<string, string> = {
	critical: "[CRITICAL]",
	high: "[HIGH]",
	medium: "[MEDIUM]",
	low: "[LOW]",
	info: "[INFO]",
};

/**
 * Format scan report as Markdown (human-readable, good for PR comments).
 */
export function formatMarkdown(report: ScanReport): string {
	const lines: string[] = [];

	// Header
	lines.push(`# ClawGuard Security Report`);
	lines.push("");
	lines.push(`**Skill:** ${report.skill.name}`);
	if (report.skill.author) lines.push(`**Author:** ${report.skill.author}`);
	if (report.skill.version) lines.push(`**Version:** ${report.skill.version}`);
	lines.push(`**Status:** ${STATUS_ICONS[report.status] ?? report.status}`);
	lines.push(`**Severity Score:** ${report.score.total}/100`);
	lines.push(`**Recommendation:** ${report.recommendation}`);
	lines.push(`**Scanned:** ${report.scannedAt}`);
	lines.push("");

	// Summary
	lines.push("## Summary");
	lines.push("");
	lines.push(`| Severity | Count |`);
	lines.push(`|----------|-------|`);
	lines.push(`| Critical | ${report.score.critical} |`);
	lines.push(`| High | ${report.score.high} |`);
	lines.push(`| Medium | ${report.score.medium} |`);
	lines.push(`| Low | ${report.score.low} |`);
	lines.push(`| Info | ${report.score.info} |`);
	lines.push("");

	// Findings
	if (report.findings.length > 0) {
		lines.push("## Findings");
		lines.push("");

		for (const finding of report.findings) {
			lines.push(
				`### ${SEVERITY_ICONS[finding.severity] ?? ""} ${finding.id}: ${finding.name}`,
			);
			lines.push("");
			lines.push(`- **Category:** ${finding.category}`);
			lines.push(`- **Scanner:** ${finding.scanner}`);
			lines.push(`- **Message:** ${finding.message}`);
			if (finding.lineNumber) {
				lines.push(
					`- **Location:** ${finding.filePath ?? "unknown"}:${finding.lineNumber}`,
				);
			}
			if (finding.evidence) {
				lines.push(`- **Evidence:** \`${finding.evidence}\``);
			}
			lines.push("");
		}
	} else {
		lines.push("## No findings");
		lines.push("");
		lines.push("No security issues were detected.");
		lines.push("");
	}

	// Scanner status
	lines.push("## Scanners");
	lines.push("");
	lines.push(`| Scanner | Status | Findings | Duration |`);
	lines.push(`|---------|--------|----------|----------|`);
	for (const s of report.scanners) {
		lines.push(
			`| ${s.scanner} | ${s.status} | ${s.findings.length} | ${s.durationMs}ms |`,
		);
	}
	lines.push("");

	lines.push("---");
	lines.push(
		"*Generated by [ClawGuard](https://clawguard.sh) — Security scanning for the skills that power your AI*",
	);

	return lines.join("\n");
}
